version: '3.8'

volumes:
  postgres_data:
  backend_static:
  backend_media:
  frontend_static:

networks:
  foodgram-network:

services:
    db:
      container_name: foodgram_db
      image: postgres:13.0-alpine
      restart: unless-stopped
      volumes:
        - postgres_data:/var/lib/postgresql/data/
      env_file:
        - ../.env
      networks:
        - foodgram-network

    backend:
      container_name: foodgram_backend
      image: octrow/foodgram_backend:latest
      restart: unless-stopped
      volumes:
        - backend_static:/app/static
        - backend_media:/app/media
      depends_on:
        - db
      env_file:
        - ../.env
      networks:
        - foodgram-network

    frontend:
      container_name: foodgram_frontend
      image: octrow/foodgram_frontend:latest
      depends_on:
        - db
        - backend
      volumes:
        - frontend_static:/app/result_build/build
      networks:
        - foodgram-network

    nginx:
      container_name: foodgram_nginx
      image: nginx:1.21.3-alpine
      restart: unless-stopped
      ports:
        - "8080:80"
      volumes:
        - ./nginx.conf:/etc/nginx/conf.d/default.conf
        - frontend_static:/usr/share/nginx/html/
        - ../docs/:/usr/share/nginx/html/api/docs/
        - backend_static:/backend_static
        - backend_media:/backend_media
      depends_on:
        - backend
        - frontend
      networks:
        - foodgram-network
